### ISSUE TITLE
[Bug] - redlock expects an array as name of keys but we pass string which results in a key per letter created

### ISSUE THREAD

**Issue by MShel** [excl-networks/strapi-plugin-redcron#2]
## Description
In the line below we pass key string to RedLock: 
https://github.com/excl-networks/strapi-plugin-redcron/blob/fe0b735d890d9e9050d29de46405136f729832f3/server/register.js#L19
Where RedLock expects to have an array:
https://github.com/mike-marcacci/node-redlock/blob/51388139356efa700f9dd4616e822eb377a47c95/src/index.ts#L297-L300
See Readme for redlock as well:
https://github.com/mike-marcacci/node-redlock/blob/51388139356efa700f9dd4616e822eb377a47c95/README.md?plain=1#L88-L89

That bug results in Redis creating locks for EACH letter of the key passed:
```
1697551106.022804 [0 lua] "exists" "r"
1697551106.022811 [0 lua] "exists" "e"
1697551106.022814 [0 lua] "exists" "d"
....
1697551106.022858 [0 lua] "set" "r" "b5025ea2f8b28035c939d36febc96854" "PX" "5000"
1697551106.022876 [0 lua] "set" "e" "b5025ea2f8b28035c939d36febc96854" "PX" "5000"
1697551106.022890 [0 lua] "set" "d" "b5025ea2f8b28035c939d36febc96854" "PX" "5000"
....
```
Which in turn brakes redCron functionality by not allowing multiple jobs to run at the same time as well as generally causing unexpected behavior

## Suggested solution
The fix would be to wrap key passed in `generateRedlockFunction` in array

**Comment by cpaczek** [comment]
Thank you, merged and published.
